bin=varub.dll
obj=vr_slist.obj vr_queue.obj vr_stack.obj vr_bitree.obj vr_rbtree.obj vr_list.obj
$(bin):$(obj)
	link /DLL /DEBUG /OUT:$@ $(obj)
.c.obj:
	cl /c $<

clean:
	del *.obj *.pdb *.ilk $(bin) *.lib *.exp
